Bump go version to 1.18
openshift/ptp-operator pull request #215
Opened 2022-08-24 15:30 UTC by bnshr

Upgrades the used package versions

2022-08-24 15:43 UTC, bnshr commented
/needs-ok-to-test

2022-08-24 15:44 UTC, bnshr commented
/ok-to-test

2022-08-25 22:45 UTC, josephdrichard requested changes
Can you put a descriptive commit message?

2022-08-26 16:48 UTC, aneeshkp commented
commit says "Initial" , add more appropriate commit description please

2022-09-05 10:39 UTC, bnshr commented
> Can you put a descriptive commit message?

Done!

2022-09-05 11:27 UTC, danielmellado commented
/lgtm

2022-09-06 13:47 UTC, aneeshkp commented
/test e2e-aws-ovn

2022-09-06 16:54 UTC, josephdrichard commented
/lgtm
/approved

2022-09-06 17:26 UTC, merged